version: '3.4'

services:
# Initial setup. Run the following command first and enter a valie fitbit refresh token
# docker-compose run publicfitbitprojects
# Then exit out with ctrl + c
# Then run docker-compose up -d to launch the full stack
  publicfitbitprojects:
    restart: unless-stopped
    image: publicfitbitprojects
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./logs:/app/logs
      - ./tokens:/app/tokens
    environment:
      - FITBIT_LOG_FILE_PATH=/app/logs/fitbit.log
      - TOKEN_FILE_PATH=/app/tokens/fitbit.token
      - OVERWRITE_LOG_FILE=True
      - FITBIT_LANGUAGE='en_US'
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_USERNAME=fitbit_user
      - INFLUXDB_PASSWORD=fitbit_password
      - INFLUXDB_DATABASE=fitbit_database
      # MAKE SURE you set the application type to PERSONAL. Otherwise, you won't have access to intraday data series, resulting in 40X errors.
      - CLIENT_ID=your_application_client_ID # Change this to your client ID
      - CLIENT_SECRET=your_application_client_secret # Change this to your client Secret
      - DEVICENAME='Your_Device_Name' # e.g. "Charge5"
      # ACCESS_TOKEN='' # Empty Global variable initialization, will be replaced with a functional access code later using the refresh code
      - AUTO_DATE_RANGE=True # Automatically selects date range from todays date and update_date_range variable
      - auto_update_date_range=1 # Days to go back from today for AUTO_DATE_RANGE *** DO NOT go above 2 - otherwise may break rate limit ***
      - LOCAL_TIMEZONE="Automatic" # set to "Automatic" for Automatic setup from User profile (if not mentioned here specifically). 
      - SCHEDULE_AUTO_UPDATE=True # if AUTO_DATE_RANGE else False # Scheduling updates of data when script runs
      - SERVER_ERROR_MAX_RETRY=3
      - EXPIRED_TOKEN_MAX_RETRY=5
      - SKIP_REQUEST_ON_SERVER_ERROR=True

  influxdb:
    restart: unless-stopped
    container_name: influxdb
    environment:
      - INFLUXDB_DB=fitbit_database
      - INFLUXDB_USER=fitbit_user
      - INFLUXDB_USER_PASSWORD=fitbit_password
    ports:
        - '8086:8086'
    volumes:
        - './influxdb:/var/lib/influxdb'
    image: 'influxdb:1.8'

  grafana:
    restart: unless-stopped
    volumes:
        - './grafana:/var/lib/grafana'
    ports:
        - '3000:3000'
    container_name: grafana
    image: 'grafana/grafana:latest'
